### ISSUE TITLE
Is there a way to set or read state using vanilla js?

### ISSUE THREAD

**Issue by markzhengma** [markzhengma/Word-Game#1]
I'm trying to play around with states in DOM of react (probably this is not suggested but I couldn't find a better way to move and detect my divs). In the gamestage component, I'm able to read the letter in the box when collision detected. In the game component, I'm able to generate random words with a state "unspelled", which is an array of letters: if the letter that user selected was the first letter in "unspelled", it would do a [...unspelled].shift(), and when the unspelled.length === 0, there will be a word save post request. Right now, the game component works and gamestage works as well, but I could not connect them.
I'm trying to pass the letter in the box in the state and check if the letter is the first letter of [...unspelled], just like the test in Game component. But now since I'm using DOM to generate the boxes and move the player, I am not really able to pass the properties of the divs as states.
I tried to do this.setstate() in the collision detection and didn't work:
collisionDetect = () => {
        setInterval(function(){
            let dude = document.getElementById('dude');
            let box = document.getElementsByClassName('box');
            let sky = document.getElementById('sky');

            [...box].forEach(function(a){
                let distance = Math.sqrt(Math.pow((a.offsetLeft - dude.offsetLeft),2) + Math.pow((a.offsetTop - dude.offsetTop),2));
                if (a.offsetLeft < -49){
                    sky.removeChild(a)
                }
                if (distance < 50){
                    console.log(a.innerHTML);
                    sky.removeChild(a);
                    this.setState({
                        word: this.state.word.push(a.innerHTML)
                    })
                }
            })
            // if (box.offsetLeft - dude.offsetLeft < 50 && box.offsetTop - dude.offsetTop < 50){
            //     console.log('hit!')
            // }
        },100)
    }
Then I tried to put div itself in the state but didn't work.
constructor(){
        super();
        this.state = {
            dude: document.getElementById('dude')
        }
}
Then I tried to setState before javascript function, something is being passed to the state but there's no offset value nor style.left value in the div.
let dude = document.createElement('div');
        this.setState({
            dude: dude
        })

Also, I tried this, no boxes showed up besides the console.log...
getBox = () => {
        console.log('created!')
        return <div class = 'box' />
    }
    render(){
        return(
            <div id = 'game-stage'>
                <div id = 'sky' onClick = {() => {setInterval(this.getBox, 1000)}}>
                    
                </div>
            </div>
        )
    }

Some links I looked at but not really helping me in this specific thing:
https://facebook.github.io/react/docs/react-dom.html
https://facebook.github.io/react/docs/conditional-rendering.html

I really need an idea here. I feel the last approach might be close, but I need a suggestion...

**Comment by jlr7245** [comment]
If you want to mix Vanilla DOM manipulation with React, you have to be very careful about it -- making sure the React component isn't going to rerender, making sure your vanilla stuff isn't going to mess up any of your react stuff, etc. Instead, try using React's built-in `onKeyPress` method to move things. It should work just about the same way. Try adding `tabIndex`es to your react elements, to make sure they can be focused on and will listen for key presses.

Also, no, you cannot access `this.state` from within a vanilla JS function -- it's a method that's only available within a class that inherits from `Component`.

Here's a little app.js that moves a div.

<details>
<summary>app.jsx</summary>

```jsx
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  constructor() {
    super();
    this.state = {
      divPosition: {
        x: 5,
        y: 5,
      },
    };
    this.moveDiv = this.moveDiv.bind(this);
  }

  moveDiv(e) {
    console.log('mvoe');
    const keyCode = e.keyCode || e.which;
    const arrow = { left: 37, up: 38, right: 39, down: 40 };

    const { x, y } = { ...this.state.divPosition };

    switch (keyCode) {
      case arrow.left:
        this.setState({
          divPosition: {
            x: x + -5,
            y: y,
          },
        });
        break;
      case arrow.right:
        this.setState({
          divPosition: {
            x: x + 5,
            y: y,
          },
        });
        break;
      case arrow.up:
        this.setState({
          divPosition: {
            x: x,
            y: y - 5,
          },
        });
        break;
      case arrow.down:
        this.setState({
          divPosition: {
            x: x,
            y: y + 5,
          },
        });
        break;
      default:
        break;
    }
  }

  render() {
    return (
      <div>
        <div
          tabIndex="0"
          onKeyDownCapture={e => this.moveDiv(e)}
          style={{
            left: `${this.state.divPosition.x}px`,
            top: `${this.state.divPosition.y}px`,
            backgroundColor: 'red',
            height: '50px',
            width: '50px',
            position: 'relative',
          }}
        >
          <p>MOVE ME AROUND</p>
        </div>
      </div>
    );
  }
}

export default App;

```
</details>

**Comment by markzhengma** [comment]
Thanks J. I'll look up for the onKeyDownCapture docs. This might be able to solve my problem!
